# combined_config.yaml
base_path: '/home/ps/dy/OpenAvatar'
K: 6
subject: '00020'
gpu_id: 0
xhuman_path: '/home/ps/dy/dataset'
configs:
  test:
    model_mode: 'edit'
    image_size: 1024
    views:
      - 'front'
    t_mesh_name: '0000_def_1.ply'
    pkl_dir: '/home/dataset/00016/test/Take1/SMPLX'
    model_name: 'model_1000.ckpt'
    need_canonical: False
    save_type: 'image'
  edit:
    image_size: 1024
    lr: 0.005
    num_epochs: 1000
    t_mesh_name: 'mesh_pred.ply'
    model_name: 'model_1300.ckpt'
  train:
    image_size: 800
    pre_num_epochs: 500
    num_epochs: 2000
    lr: 0.005
    t_mesh_name: '0000_def_1.ply'