# combined_config.yaml
base_path: '/home/ps/dy/OpenAvatar'
K: 6
subject: '00017'
gpu_id: 0
xhuman_path: '/home/ps/dy/dataset'
configs:
  test:
    model_mode: 'val'
    image_size: 1024
    views:
      - 'front'
    t_mesh_name: '0000_def_1.ply'
    pkl_dir: '/home/ps/dy/mycode2/t0627/testpkl'
    model_name: 'model_300.ckpt'
    need_canonical: True
    save_type: 'mesh'
  edit:
    image_size: 1024
    lr: 0.005
    num_epochs: 1000
    t_mesh_name: 'mesh_pred.ply'
    model_name: 'model_1300.ckpt'
  train:
    image_size: 800
    pre_num_epochs: 500
    num_epochs: 2000
    lr: 0.005
    t_mesh_name: '0000_def_1.ply'