# combined_config.yaml
base_path: '/home/ps/dy/OpenAvatar'
K: 6
subject: '00021'
gpu_id: 0
xhuman_path: '/home/ps/dy/dataset'
geometry_model_path: '/home/ps/dy/X-Avatar/outputs/XHumans_smplx/00021_delta'
configs:
  test:
    model_mode: 'val'
    image_size: 1024
    views:
      - 'front'
    t_mesh_name: 't_mesh.ply'
    pkl_dir: '/home/ps/dy/dataset/00021/test'
    model_name: 'model_500.ckpt'
    need_canonical: True
    save_type: 'mesh'  # 'image' or 'mesh'
  edit:
    image_size: 1024
    lr: 0.005
    num_epochs: 1000
    t_mesh_name: 'mesh_pred.ply'
    model_name: 'model_500.ckpt'
  train:
    image_size: 800
    pre_num_epochs: 200
    num_epochs: 500
    lr: 0.005
    t_mesh_name: 't_mesh.ply'
  fit:
    image_size: 1024
    num_epochs: 50
    lr: 0.001
    t_mesh_name: 't_mesh.ply'
    init_model_path: 'model_500.ckpt'
