subject: '00000'
base_path: '/home/ps/data/dy/CtrlAvatar'
data_path: '/home/ps/data/dy/dataset/S4d'
K: 6
gpu_id: 0
renderer_type: 'nvdiff' # pytorch3d or nvdiff
geometry_model_path: 'geometry/outputs/Dress_smplx/00000'
configs:
  test:
    model_mode: 'val'
    image_size: 1024
    views:
      - 'front'
    t_mesh_name: 't_mesh_2.ply'
    model_name: 'model_20.ckpt'
    need_canonical: True
    save_type: 'mesh'  # 'image' or 'mesh'
    pkl_dir: '/home/ps/dy/dataset/S4d/00122_Inner/test'
  edit:
    image_size: 1024
    lr: 0.005
    num_epochs: 1000
    t_mesh_name: 'mesh_pred.ply'
    model_name: 'model_500.ckpt'
  train:
    image_size: 2048
    pre_num_epochs: 200
    num_epochs: 500
    lr: 0.005
    t_mesh_name: 't_mesh.ply'
  fit:
    image_size: 1024
    num_epochs: 50
    lr: 0.001
    t_mesh_name: 't_mesh.ply'
    init_model_path: 'model_500.ckpt'