base_path: '/home/ps/dy/CtrlAvatar'
subject: '00000'
gpu_id: 0
data_path: '/home/ps/dy/dataset/SCHuman'
geometry_model_path: 'geometry/outputs/CHumans_smplx/00000_delta'
renderer_type: 'pytorch3d'
configs:
  test:
    model_mode: 'train'
    image_size: 1024
    views:
      - 'front'
    t_mesh_name: 't_mesh.ply'
    pkl_dir: '/home/ps/dy/chuman/00000/test'
    model_name: 'model_50.ckpt'
    need_canonical: True
    save_type: 'mesh'  # 'image' or 'mesh'
  edit:
    image_size: 1024
    lr: 0.005
    num_epochs: 1000
    t_mesh_name: 'mesh_pred.ply'
    model_name: 'model_500.ckpt'
  train:
    image_size: 800
    pre_num_epochs: 200
    num_epochs: 500
    lr: 0.005
    t_mesh_name: 't_mesh.ply'
  fit:
    image_size: 1024
    num_epochs: 50
    lr: 0.001
    t_mesh_name: 't_mesh.ply'
    init_model_path: 'model_500.ckpt'
